services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autoparts_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=${DB_HOST:-host.docker.internal}
      - DB_USER=autoparts_user
      - DB_PASSWORD=autoparts_password
      - DB_NAME=autoparts_webhub_db
      - DB_PORT=3306
      - AUTH_GOOGLE_ID=259982290521-it6hea8avuhjcib8rtfmtgoissl0k6dl.apps.googleusercontent.com
      - AUTH_GOOGLE_SECRET=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
      - AUTH_SECRET=7a0e38bc86f1e1493012a67be92c19e830e2f89c09c91656b825da1123f1ba9c
      - AUTH_TRUST_HOST=true
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"

