sonar.projectKey=autoparts-backend
sonar.projectName=AutoParts WebHub Backend
sonar.projectVersion=1.0.0

# Paths to sources and tests
sonar.sources=src
sonar.exclusions=src/**/*.test.ts,src/**/*.spec.ts,node_modules/**
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.spec.ts

# Jest Coverage Report
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/app.ts,src/config/**/*,src/routes/**/*,src/controllers/parts.controller.ts,src/controllers/appointments.controller.ts,src/controllers/settings.controller.ts,src/controllers/users.controller.ts,src/controllers/vehicles.controller.ts,src/middlewares/**/*

# Connection to SonarQube Server
sonar.host.url=http://localhost:9000

# Authentication Token
sonar.token=squ_b0030f669aad254ea3b7c8d2e35139a0429b2e1b
